### ISSUE TITLE
premul_table symbol(s) not found for architecture x86_64

### ISSUE THREAD

**Issue by BennyKJohnson** [Marginal/QLdds#1]
Hi,

I attempted to use this source code for dds reading in my own project. I only require the dds.h and dds.m source files. When I went to build I received a linker error. I worked out that this is due to the extern variable premul_table.  Am I missing an external library or a header? How do I solve this?

![image](https://cloud.githubusercontent.com/assets/7237725/10298298/143a2ba0-6c29-11e5-9975-7a820744a391.png)

Thanks

**Comment by Marginal** [comment]
premul_table is defined [here](https://github.com/Marginal/QLdds/blob/master/qlgenerator/main.c#L27) and initialised [here](https://github.com/Marginal/QLdds/blob/master/qlgenerator/main.c#L97). You will need to do the same somewhere in your code if you intend to call any of the functions that unpack the image data.

Alternatively, you could get rid of premul_table by replacing the [premultiply](https://github.com/Marginal/QLdds/blob/master/DDS/dds.m#L131) function with something like [this](https://github.com/mozilla-services/services-central-legacy/blob/master/gfx/thebes/gfxColor.h#L107).
