### ISSUE TITLE
No working on Mac

### ISSUE THREAD

**Issue by JordanMachado** [Marginal/QLdds#3]
Hi there,

I know it's a bit annoying to see people write not working. but I would like to know was is your OS version.

I tried on : 
macOs Sierra 
Version 10.12.6
MacBook Pro (Retina, 15-inch, Mid 2014)

**Comment by Marginal** [comment]
Tested on 10.6, 10.9, 10.12, 10.13.

Please try with these files: [747_Fuselage.zip](https://github.com/Marginal/QLdds/files/1423163/747_Fuselage.zip)

If these don't work then please:
- Run the Terminal app
- Type `qlmanage -d1 -p /path/to/a/file.dds`, substituting /path/to/a/file.dds with the path to one of the attached DDS files by dragging the file from the Finder window to the Terminal window, and press Enter.
- Copy the contents of the Terminal window and paste here.

**Comment by wumingbo** [comment]
hi, it's mine...^_^
dMacBook-Pro:game-v1 wl$ sudo qlmanage -d1 -p cube.dds 
Testing Quick Look preview with files:
	cube.dds
[DEBUG] Preview test for cube.dds -- file:///Users/game/gametest/game-v1/. Content type UTI: com.microsoft.dds
[DEBUG] Previewing file:///Users/game/gametest/game-v1/cube.dds. Content type UTI: com.microsoft.dds. Generator used: <QLGenerator /Library/QuickLook/QLdds.qlgenerator>
[DEBUG] Loading <QLGenerator /Library/QuickLook/QLdds.qlgenerator>
[DEBUG] Previewing file:///Users/game/gametest/game-v1/cube.dds did not produce anything
[DEBUG] Thumbnailing cube.dds -- file:///Users/game/gametest/game-v1/ - type: com.microsoft.dds - generator: <QLGenerator /Library/QuickLook/QLdds.qlgenerator> (try #1)
[DEBUG] Thumbnailing file:///Users/game/gametest/game-v1/cube.dds. Content type UTI: com.microsoft.dds. Generator used: <QLGenerator /Library/QuickLook/QLdds.qlgenerator>
[DEBUG] Thumbnailing file:///Users/game/gametest/game-v1/cube.dds did not produce anything
2018-04-11 14:10:25.113 qlmanage[655:12995] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0x9e03, name = 'com.apple.coredrag'
See /usr/include/servers/bootstrap_defs.h for the error codes.
2018-04-11 14:10:25.180 qlmanage[655:12995] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0xc937, name = 'com.apple.tsm.portname'
See /usr/include/servers/bootstrap_defs.h for the error codes.
2018-04-11 14:10:25.184 qlmanage[655:12995] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0xcc03, name = 'com.apple.CFPasteboardClient'
See /usr/include/servers/bootstrap_defs.h for the error codes.

**Comment by wumingbo** [comment]
![t](https://user-images.githubusercontent.com/5779168/38600822-200f1aa6-3d98-11e8-92c3-641944ee8f1f.jpg)

hi my file is "pvr4", not working
747_Fuselage.zip is "ati2" is fine!

**Comment by wumingbo** [comment]
hi my file is "pvr4", not working
747_Fuselage.zip is "ati2" is fine!

**Comment by Marginal** [comment]
@wumingbo Please zip up your file and attach it here.
